package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with absolute id = 'ProjectWithSubprojects2_HttpsGithubComInnayanFortemp1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id = AbsoluteId("ProjectWithSubprojects2_HttpsGithubComInnayanFortemp1")
    name = "https://github.com/innayan/fortemp1"
    url = "https://github.com/innayan/fortemp1"
    authMethod = password {
        userName = "innayan"
        password = "credentialsJSON:8b81c90d-e4be-4b96-bd84-fdf57a093314"
    }
}))

